### ISSUE TITLE
Error loading on dedicated server

### ISSUE THREAD

**Issue by Rakambda** [comp500/demagnetize#10]
Trying to load the mod on a dedicated server results in a crash because it tries to load a client only class.

```
[19Oct2019 10:50:27.601] [Server thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[19Oct2019 10:50:27.602] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Demagnetize (demagnetize) has failed to load correctly
§7Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:199) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:181) ~[?:?]
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```

Forge version: `1.14.4-28.1.61`
Demagnetize version: `1.14.4-1.2.0`

[Crash log](https://pastebin.com/uHFZYk8m)
[Debug log](https://pastebin.com/3B6tdXGK)

**Comment by comp500** [comment]
Thanks, I'll look into it.

**Comment by comp500** [comment]
I found where the error is being caused and have fixed it. However, I also found another crash that occurs when you open the Demagnetizer GUI, which I think should be fairly easy to fix.
